In [1]:
!pip install requests

Requirement already satisfied: requests in C:\Users\KIIT0001\.conda\envs\myenv\Lib\site-packages (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\KIIT0001\.conda\envs\myenv\Lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\KIIT0001\.conda\envs\myenv\Lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\KIIT0001\.conda\envs\myenv\Lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\KIIT0001\.conda\envs\myenv\Lib\site-packages (from requests) (2026.4.22)

In [7]:
#API--->free-apis.github.io/#/
import requests

In [8]:
URL="https://stephen-king-api.onrender.com/api/books"
res=requests.get(URL)

In [9]:
res

In [10]:
json_data=res.json()

In [11]:
import pandas as pd
df=pd.json_normalize(json_data["data"])
df=df[["id","Title","Year","ISBN"]]

In [12]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [13]:
#WEB SCRAPING-->scrapethissite.com
import requests

In [14]:
URL="https://www.scrapethissite.com/pages/simple/"
res=requests.get(URL)
print(res.status_code)

200

In [15]:
if res.status_code==200:
    print(res.headers)

    
#saving html(res.text) in our scraped_data file
with open("scraped_data/data1.html","w",encoding="utf-8") as f:
    f.write(res.text)

{'Date': 'Thu, 30 Apr 2026 22:51:57 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=n617VnSeTCEeVEra2x3KSQ8DHTCRNC%2FzJTSLtom7f0o%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1777589516"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=n617VnSeTCEeVEra2x3KSQ8DHTCRNC%2FzJTSLtom7f0o%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1777589516"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'br', 'CF-RAY': '9f4a1d2f9d20e231-MRS', 'alt-svc': 'h3=":443"; ma=86400'}

In [16]:
#BEAUTIFULSOUP
from bs4 import BeautifulSoup

In [17]:
with open("scraped_data/data1.html","r",encoding="utf-8") as f:
    html_content=f.read()

soup=BeautifulSoup(html_content,"lxml")

In [22]:
soup.find("h3")

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [61]:
all_h3=soup.find_all("h3")
all_countries=[]
for h3 in all_h3:
    name=(h3.get_text(strip=True))
    #print(h3.find_parent("div")["class"])
    population=(h3.find_next("div").select_one("span.country-population").get_text(strip=True))
    all_countries.append([name,population])

In [64]:
import pandas as pd
df=pd.DataFrame(all_countries,columns=["Name","Population"])

In [65]:
df

                     Name Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

In [66]:
df.to_csv("cleaned(s)_data/data.csv",index=False)